project:
  type: book

book:
  title: "Zbiór zadań - C"
  author: Piotr Jastrzębski
  date: today
  cover-image: logo-c.jpg
  chapters:
    - index.qmd
    - part: "Podstawy języka C"
      chapters: 
       - operacjewejsciawyjscia.qmd
       - intrukcjewarunkowe.qmd
       - petle.qmd
       - funkcje.qmd
       - wskazniki.qmd
       - wskaznikinafunkcje.qmd
       - debugowanie.qmd
    - part: "Dodatki"
      chapters: 
        - printf-formatowanieliczb.qmd
        - operatoryarytmetyczne.qmd
        - operatorybitowe.qmd
    - references.qmd
    - changelog.qmd
  downloads: pdf
  repo-url: https://github.com/pjastr/zbior-zadan-c
  repo-actions: [issue]


bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: solar
    lang: pl
  pdf:
    lang: pl
    header-includes: |
      \titlehead{\includegraphics[width=6in]{logo-c.jpg}}


editor: visual

